name: Pull Requests

on:
  pull_request:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Docker Buildx
      id: master
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        buildx-version: latest
        qemu-version: latest
    - name: Run go report card on PR
      run: make score GITOPS_API_KEY=${{ secrets.GITOPS_API_KEY }} GITHUB_USER=gogitops GITHUB_TOKEN=${{secrets.GITHUB_API_TOKEN}}
    - name: Build the Server Docker image
      run: make docker_build APP_TYPE=server
    - name: Build the Client Docker image
      run: make docker_build APP_TYPE=client DOCKERFILE=Dockerfile.client