name: Pull Requests

on:
  pull_request:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run go report card on PR
      run: make score GITOPS_API_KEY=${{ secrets.GITOPS_API_KEY }} GITHUB_USER=gogitops GITHUB_TOKEN=${{secrets.GITHUB_API_TOKEN}}
    - name: Build the ARM Docker image
      run: make docker_build ARCH=arm APP_TYPE=server
    - name: Build the amd64 Docker image
      run: make docker_build GOARCH=amd64 APP_TYPE=server
    - name: Build the arm Client Docker image
      run: make docker_build GOARCH=arm APP_TYPE=client
    - name: Build the amd64 Client Docker image
      run: make docker_build GOARCH=amd64 APP_TYPE=client