name: Pull Requests

on:
  pull_request:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run go report card on PR
      run: make score GITOPS_API_KEY=${{ secrets.GITOPS_API_KEY }} GITHUB_USER=gogitops GITHUB_TOKEN=${{secrets.GITHUB_API_TOKEN}}
    - name: Build the ARM Docker image
      run: make docker_build ARCH=arm TYPE=server
    - name: Push the ARM Docker image
      run: make docker_push ARCH=arm TYPE=server  DOCKER_USER=beaujr DOCKER_PASS=${{ secrets.DOCKER_PASS }}
    - name: Build the amd64 Docker image
      run: make docker_build GOARCH=amd64 TYPE=server
    - name: Build the amd64 Docker image
      run: make docker_push GOARCH=amd64 TYPE=server DOCKER_USER=beaujr DOCKER_PASS=${{ secrets.DOCKER_PASS }}