name: Pull Requests

on:
  pull_request:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    - name: Docker Login
      run: make docker-login DOCKER_USER=beaujr DOCKER_PASS=${{ secrets.DOCKER_PASS }}
    - name: Build the ARM Server Docker image
      run: make docker_build APP_TYPE=server PLATFORM=linux/arm/v7,linux/arm/v6 BUILD_TAG=arm-server
    - name: Build the Client Docker image
      run: make docker_build APP_TYPE=client DOCKERFILE=Dockerfile.client PLATFORM=linux/arm/v7,linux/arm/v6 BUILD_TAG=arm-client