name: Pull Requests

on:
  pull_request:
    branches:
    - 'master'

jobs:
  score:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GoGitOps Step
        id: gogitops
        uses: beaujr/gogitops-action@v0.2
        with:
          github-actions-user: github-actions
          github-actions-token: ${{secrets.GITHUB_TOKEN}}
  build-binary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.x
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: --snapshot --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}