name: Pull Requests

on:
  pull_request:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Build AMD64 Binary
      run: make build GOARCH=amd64 GOOS=linux
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/mything
        asset_name: bin/beaujr/nmap_prometheus-client
        tag: amd64
        overwrite: true
        body: "AMD64 Client Release"
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/beaujr/nmap_prometheus-client
        asset_name: Latest
        tag: amd64
        overwrite: true
        body: "AMD64 Client Release"
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Docker Login
      run: make docker-login DOCKER_USER=beaujr DOCKER_PASS=${{ secrets.DOCKER_PASS }}
    - name: Build the Client Docker image
      run: make docker_build APP_TYPE=client DOCKERFILE=Dockerfile.client BUILD_TAG=client-unstable PUSH=false
    - name: Build the Server Docker image
      run: make docker_build APP_TYPE=server BUILD_TAG=server-unstable PUSH=false